blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('detail/<int:post_id>', views.detail_post, name='detail-post'), 
    path('category/<ctg_name>', views.category_by_list, name='category-list'), 
    path('search', views.search_post, name='search'),
    path('create/post', views.create_post, name='create-post'),
    

]

wordify/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),


]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager




class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=50)
    photo = models.ImageField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = TaggableManager()


    def __str__(self):
        return "{} - {}".format(self.title, self.author)

    def get_absolute_url(self):
        return "/blog/detail/{}" .format(self.id)
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Post, Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'category', 'tags', 'photo')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'tags': forms.TextInput(attrs={'class': 'form-control', 'data-role': 'tagsinput'}),
            'photo': forms.FileInput(),


        }

blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from taggit.models import Tag
from .models import Category, Post, Comment
from .forms import *
#from django.template.defaultfilters import slugify


def create_post(request):
    forms = CreatePostForm()
    common_tags = Post.tags.most_common()[:4]

    if request.method == 'POST':
        forms = CreatePostForm(request.POST, request.FILES)
        if forms.is_valid():
            post_form = forms.save(commit=False)
            post_form.author = request.user
            post_form.save()
            forms.save_m2m()
            return redirect('/')
    context = {
        'forms': forms,
        'common_tags': common_tags

    }
    return render(request, "blog/create_post.html", context)

def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    common_tags = Post.tags.most_common()[:4]
    posts = Post.objects.filter(tags=tag)
    context = {
        'tag':tag,
        'common_tags':common_tags,
        'posts':posts,
    }
    return render(request, 'blog/create_post.html', context)


def search_post(request):
    if request.method == 'POST':
        search_keyword = request.POST['search_keyword']
        posts = Post.objects.filter(title__contains=search_keyword)
        return render(request, 'blog/search.html',{'posts': posts, 'search_key': search_keyword})
    
    return render(request, 'blog/search.html')


def detail_post(request, post_id):
    try:
        post_obj = Post.objects.get(id=post_id)
        #profile_obj = Profile.objects.get(user=post_obj.author)
        comments = post_obj.comments.all()
        form = CommentForm()
        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                comment_form = form.save(commit=False)
                comment_form.post = post_obj
                comment_form.save()
                return redirect(post_obj)

        context = {
            'post': post_obj, 
            'comments': comments, 
            'form': form
            }
        return render(request, 'blog/detail_post.html', context)
    except:
        return render(request, '404.html')

def category_by_list(request, ctg_name):
    cteg_obj = Category.objects.get(name=ctg_name)
    post_list = Post.objects.filter(category=cteg_obj)
    context = {'posts': post_list, 'catg_name': ctg_name}
    return render(request, 'blog/post_by_category.html', context)

templates/blog/create_post.html
{% extends "dashbord_base/base.html" %}


{% block content %}

{% for error in forms.errors %}
<p class="text-danger">{{ error }}</p>
  
{% endfor %}

<div class="card">
    <div class="card-header">Create New Post</div>
    <div class="card-body">
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in forms %}
    <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
    </div>
    {% endfor %}
    <input type="submit" value="Submit" class="btn btn-success" name="" id="">
</form>
<p>Common Tags: 
    {% for mt in common_tags %}
        <a href="#" class="badge badge-success">{{mt}}</a>
    {% endfor %}
    </p>
</div>
</div>
{% endblock  %}


<!-- <form action="" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="csrfmiddlewaretoken" value="vr6Q5KukxVOq60UaSooMkbrLRI0HDPb0QuJ9JqPjGHV6vLYJe032AQfJqecslMPI">
    
    <div class="form-group">
        <label for="id_title">Title:</label>
        <input type="text" name="title" class="form-control" maxlength="50" required="" id="id_title">
    </div>
    
    <div class="form-group">
        <label for="id_body">Body:</label>
        <textarea name="body" cols="40" rows="10" class="form-control" required="" id="id_body" spellcheck="false"></textarea>
    </div>
    
    <div class="form-group">
        <label for="id_category">Category:</label>
        <select name="category" class="form-control" required="" id="id_category">
  <option value="" selected="">---------</option>

  <option value="1">Food</option>

  <option value="2">Travel</option>

  <option value="3">Lifestyle</option>

  <option value="4">Programming</option>

</select>
    </div>
    
    <div class="form-group">
        <label for="id_tags">Tags:</label>
        <input type="text" name="tags" required="" id="id_tags">
    </div>
    
    <div class="form-group">
        <label for="id_photo">Photo:</label>
        <input type="file" name="photo" accept="image/*" required="" id="id_photo">
    </div>
    
    <input type="submit" value="Submit" class="btn btn-success" name="" id="">
</form> -->

templates/blog/detail_post.html
{% extends 'base.html' %}

{% block content %}

    <div class="col-md-12 col-lg-8 main-content">
            <img src="{{ post.photo.url }}" alt="Image" class="img-fluid mb-5">
            <div class="post-meta">
                <span class="author mr-2"><img src="{{ post.author.profile.photo.url }}" alt="" class="mr-2">
                 {{ post.author.profile.user.username|lower }}</span>&bullet;
                <span class="mr-2">{{ post.date }}</span> &bullet;
            </div>
          
            <h1 class="mb-4">{{ post.title }}</h1>
            Tags -
            {% for tag in post.tags.all %}
            <a class="category mb-5" href="#">{{ tag }}</a>
            {% endfor %}
            <br>
            Category - 
            <a class="category mb-5" href="{% url 'category-list' post.category %}">{{ post.category }}</a>
           
            <div class="post-content-body">
              <p>{{ post.body }}</p>
            
            </div>
    </div>


    <div class="pt-5">

      <h3 class="mb-5"> {{ post.comments.all|length }} Comments</h3>

      <ul class="comment-list">
        
        {% if comments %}
            {% for comment in comments %}
              
        <li class="comment">
          
          <div class="comment-body">
            <h3>{{ comment.name }}</h3>
            <p>{{ comment.body }}</p>
            
          </div>
        </li>
        {% endfor %}

        {% else %}
        <h3>No Comments Found !!</h3>

        {% endif %}


      </ul>


      <!-- END comment-list -->
      
      <div class="comment-form-wrap pt-5">
        <h3 class="mb-5">Leave a comment</h3>
        <form action="" method="POST" class="p-5 bg-light">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Post Comment" class="btn btn-primary">
        </form>
      </div>
    </div>



{% endblock  %}



<!-- END comment-list
  <div class="form-group">
    <label for="name">Name *</label>
    <input type="text" class="form-control" id="name">
  </div>
  <div class="form-group">
    <label for="email">Email *</label>
    <input type="email" class="form-control" id="email">
  </div>
  
  <div class="form-group">
    <label for="message">Message</label>
    <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
  </div>
  <div class="form-group">
    <input type="submit" value="Post Comment" class="btn btn-primary">
  </div>
   -->

  

templates/blog/post_by_category.html
{% extends 'base.html' %}

{% block content %}

            <div class="row">

          <div class="container">
          
             <div class="col-md-6">
              <h2 class="mb-4">{{ catg_name }} Category</h2>
            </div>
          </div>
           

            {% for post in posts %}
                <div class="col-md-6">
                  <a href="{% url 'detail-post' post.id %}" class="blog-entry element-animate" data-animate-effect="fadeIn">
                    <img src="{{ post.photo.url }}" alt="Image placeholder">
                    <div class="blog-content-body">
                      <div class="post-meta">
                        <span class="author mr-2"><img src="{{ post.author.profile.photo.url }}" alt="Colorlib"> {{ post.author.profile.full_name }}</span>&bullet;
                        <span class="mr-2">{{ post.date }}</span>
                      </div>
                      <h2>{{ post.title }}</h2>
                    </div>
                  </a>
                </div>
            {% endfor %}
              </div>

              

{% endblock %}

templates/blog/search.html
{% extends 'base.html' %}

{% block content %}

<div class="row">

          <div class="container">
          
             <div class="col-md-6">
              <h2 class="mb-4">Search For {{ search_key }}</h2>
            </div>
          </div>
           
        {% if posts %}

            {% for post in posts %}

                <div class="col-md-6">
                  <a href="{% url 'detail-post' post.id %}" class="blog-entry element-animate" data-animate-effect="fadeIn">
                    <img src="{{ post.photo.url }}" alt="Image placeholder">
                    <div class="blog-content-body">
                      <div class="post-meta">
                        <span class="author mr-2"><img src="{{ post.author.profile.photo.url }}" alt="Colorlib"> {{ post.author.profile.full_name }}</span>&bullet;
                        <span class="mr-2">{{ post.date }}</span>
                      </div>
                      <h2>{{ post.title }}</h2>
                    </div>
                  </a>
                </div>

            {% endfor %}
        {% else %}

            <div class="container">
          
              <h2 class="mb-4">No post Found about {{ search_key }}</h2>
            
          </div>

        {% endif %}
        </div>

              <div class="row mt-5">
                <div class="col-md-12 text-center">
                  <nav aria-label="Page navigation" class="text-center">
                    <ul class="pagination">
                      <li class="page-item  active"><a class="page-link" href="#">&lt;</a></li>
                      <li class="page-item"><a class="page-link" href="#">1</a></li>
                      <li class="page-item"><a class="page-link" href="#">2</a></li>
                      <li class="page-item"><a class="page-link" href="#">3</a></li>
                      <li class="page-item"><a class="page-link" href="#">4</a></li>
                      <li class="page-item"><a class="page-link" href="#">5</a></li>
                      <li class="page-item"><a class="page-link" href="#">&gt;</a></li>
                    </ul>
                  </nav>
                </div>
              </div>

{% endblock  %}





              